[workspace.package]
authors = ["Paul Sobolik <psobolik@zoho.com>"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "shared",
    "processor",
    "cli",
    "webservice"
]
